---
title: "git.command"
output: html_document
---

**name of the file without . to clear the confusion for interreption **

# Basic Git (trying log and reset, diff)

## Repo, commit, diff, tag
* repo : the files 
* commit : hinds of changes
* diff : the difference between versions
* tag : like a nickname of the version

## Bacis commands 

### From Morvan
#### log and diff
* workflow : four stages, untracked unmodified, modified, staged
    * the flow : untrack(add)staged(commit)unmodified(editing)modified(add)staged(commit)unmodified ......
    * **add** : regardless current stage, this will command to staged stage which is ready for commit: 
        * first time : untracked to staged 
        * after first time : modified to stage
    * **commit** : from staged to unmodified which is ready for push to remote
    * **while editing** : the unmodified to modified
* log : the record of changed content
    * git log : show the previous record of change
* checking the difference between current modified file (unstaged which hasn't added) and previous record in the git
    * a/git : previous git file
    * b/git : current saved file
    * **diff** : the different between a/git and b/git, between modified and unmodified
        * git diff 
        * git status -s : chech the stages 
* checking the difference between staged and modified 
    * git diff --cached
* checking the difference between unadded and added
    * git diff HEAD
* git add . : add all files




### from githun and rstudio
#### clone and record 
* git clone : the clone the whole file form remote repo
* git status 
* git log 
* git log --online : show the record with SHAD (7letters)
#### remote
* git remote add origin url : add a remote to existing local repo
* git remote --verbose : checking the remote
* git remote show origin : checkiing the remote in details
#### push
* git push --set-upstream origin master : push local master to github master and lave local master track master on github
* git push -u origin master : once only
#### regular push
* git push
* git push origin master
#### pull
* git pull : keep the local file up-to-date
* git pull --ff-only : **pull commits and don't let it ptu yuo in a merge conflic pickle**
* **git fetch** 
* git checkout [branch-name]: switch to a brance
#### checking 
* git remote -v
* git branch -vv




